
tasks:
  - init: npm install 
    command: npm run dev


ports:
  - port: 5000
    visibility: public
    onOpen: open-browser

  - port: 35729
    visibility: public
    onOpen: ignore
    
vscode:
  extensions:
    - streetsidesoftware.code-spell-checker
    - streetsidesoftware.code-spell-checker-russian
