# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
  #- mkdir .public
  #- cp -r * .public
  # - mv public .public
  # - mv .public public
    - echo "nothing to do"
  artifacts:
    paths:
    - public
  only:
  - pages
Ñ‘